name: "Setup Surfpool"
description: "Installs and caches the Surfpool CLI"
runs:
  using: "composite"
  steps:
    - uses: actions/cache@668228422ae6a00e4ad889ee87cd7109ec5666a7 # v5
      name: Cache Surfpool Binary
      id: cache-surfpool
      with:
        path: /usr/local/bin/surfpool
        # TODO: currently this value is only used to invalidate the cache and install latest, it is not
        # actually installing the specified version.
        # Issue: https://github.com/solana-foundation/anchor/issues/4160
        key: surfpool-${{ runner.os }}-v${{ env.SURFPOOL_CLI_VERSION }}

    - uses: nick-fields/retry@ad984534de44a9489a53aefd81eb77f87c70dc60 # v4
      if: steps.cache-surfpool.outputs.cache-hit != 'true'
      with:
        retry_wait_seconds: 300
        timeout_minutes: 2
        max_attempts: 10
        retry_on: error
        shell: bash
        command: |
          set -euxo pipefail
          echo "Installing Surfpool version ${{ env.SURFPOOL_CLI_VERSION }}"
          curl -sL https://run.surfpool.run/ | VERSION=v${{ env.SURFPOOL_CLI_VERSION }} bash
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          echo "$PATH"
          ls -al $HOME/.local/bin

    

