# Linters that run on everything and don't exclude docs/**
name: Global Linters
on:
  workflow_dispatch:
  pull_request:

# Manually run cspell locally via:
#    make spellcheck
jobs:
  spellcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      # Pinned version of the v7.2.0 tag, which is a lightweight and hence mutable tag
      - uses: streetsidesoftware/cspell-action@9cd41bb518a24fefdafd9880cbab8f0ceba04d28 #v8
        with:
          # For now, only lint markdown files
          files: |
            **/*.md
            **/*.mdx
          inline: warning

          # Only check files in the PR or push
          incremental_files_only: true

          # Do not error out on failures, only complain
          strict: false
