name: No Unpinned Docker Images

on:
  push:
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out source
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - run: chmod 755 ./docker/check-docker-pin.sh
      - run: ./docker/check-docker-pin.sh