name: Publish npmjs

on:
  workflow_call:
    inputs:
      dry_run:
        description: "If true, use --dry-run instead of actually publishing"
        required: true
        type: boolean

jobs:
  publish-npmjs-dry-run:
    name: Publish npmjs packages (dry-run)
    if: ${{ inputs.dry_run }}
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
        with:
          node-version: "24"
          registry-url: "https://registry.npmjs.org"
          package-manager-cache: false

      - name: Enable corepack (yarn)
        run: corepack enable

      - name: Publish npmjs packages
        env:
          DRY_RUN: "true"
        run: bash .github/scripts/publish-npmjs.sh

  publish-npmjs:
    name: Publish npmjs packages
    if: ${{ !inputs.dry_run }}
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    environment:
      name: release
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2

      - uses: actions/setup-node@53b83947a5a98c8d113130e565377fae1a50d02f # v6
        with:
          node-version: "24"
          registry-url: "https://registry.npmjs.org"
          package-manager-cache: false

      - name: Enable corepack (yarn)
        run: corepack enable

      - name: Publish npmjs packages
        env:
          DRY_RUN: "false"
        run: bash .github/scripts/publish-npmjs.sh
